# SPDX-License-Identifier: Apache-2.0

name: Lint Markdown documents

on:
  push:
    branches:
      - "main"
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.yaml'
      - '.github/workflows/docs.yml' # This workflow
  pull_request:
    branches:
      - "main"
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.yaml'
      - '.github/workflows/docs.yml' # This workflow

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: "Check Markdown documents"
        uses: DavidAnson/markdownlint-cli2-action@eb5ca3ab411449c66620fe7f1b3c9e10547144b0 # v18.0.0
        with:
          globs: '**/*.md'
